AWSTemplateFormatVersion: "2010-09-09"
Description: "EC2 instance with parameters"
Parameters:
  AMI:
    Description: this is ec2 description for ami in us-east-1
    Type: String
    Default: ami-02e136e904f3da870
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
  Subnet:
    Type: AWS::EC2::Subnet::Id

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AMI
      InstanceType: !Ref InstanceType
      SubnetId: !Ref Subnet
      Tags:
        - Key: Name
          Value: learn-cloudformation-2-parameters
  EC2Instance2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AMI
      InstanceType: !Ref InstanceType
      SubnetId: !Ref Subnet
      Tags:
        - Key: Name
          Value: learn-cloudformation-3-parameters

Outputs:
  OutputOfEC2Id: 
    Value: !Ref EC2Instance
    OutputOfEC2Id:
    Value: !Ref EC2Instance2