AWSTemplateFormatVersion: '2010-09-09'
Description:  "Dimple patel S3 bucket using cloudformation template"

Resources:
  MyS3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "dimpat-10272021"